[2021-04-04 22:00:35,551] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-04-04T00:00:00+00:00 [queued]>
[2021-04-04 22:00:35,555] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-04-04T00:00:00+00:00 [queued]>
[2021-04-04 22:00:35,556] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-04 22:00:35,556] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-04 22:00:35,556] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-04 22:00:35,566] {taskinstance.py:1063} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-04-04T00:00:00+00:00
[2021-04-04 22:00:35,569] {standard_task_runner.py:52} INFO - Started process 7677 to run task
[2021-04-04 22:00:35,575] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2021-04-04T00:00:00+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpkikdt5fz', '--error-file', '/tmp/tmp2mbuen7w']
[2021-04-04 22:00:35,576] {standard_task_runner.py:77} INFO - Job 9: Subtask is_api_available
[2021-04-04 22:00:35,604] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2021-04-04T00:00:00+00:00 [running]> on host prathamesh-VirtualBox
[2021-04-04 22:00:35,627] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-04-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-04T00:00:00+00:00
[2021-04-04 22:00:35,627] {http.py:102} INFO - Poking: api/
[2021-04-04 22:00:35,630] {base.py:65} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: None
[2021-04-04 22:00:35,631] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-04-04 22:00:35,858] {base.py:245} INFO - Success criteria met. Exiting.
[2021-04-04 22:00:35,863] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20210404T000000, start_date=20210405T020035, end_date=20210405T020035
[2021-04-04 22:00:35,902] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-04-04 22:00:35,937] {local_task_job.py:146} INFO - Task exited with return code 0
