[2021-04-04 22:31:55,957] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-04-05T02:27:23.398734+00:00 [queued]>
[2021-04-04 22:31:55,964] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-04-05T02:27:23.398734+00:00 [queued]>
[2021-04-04 22:31:55,965] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-04 22:31:55,965] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-04 22:31:55,965] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-04 22:31:55,989] {taskinstance.py:1063} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-04-05T02:27:23.398734+00:00
[2021-04-04 22:31:55,999] {standard_task_runner.py:52} INFO - Started process 3493 to run task
[2021-04-04 22:31:56,013] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2021-04-05T02:27:23.398734+00:00', '--job-id', '19', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpq6tmogf9', '--error-file', '/tmp/tmpr7utujcb']
[2021-04-04 22:31:56,013] {standard_task_runner.py:77} INFO - Job 19: Subtask is_api_available
[2021-04-04 22:31:56,060] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2021-04-05T02:27:23.398734+00:00 [running]> on host prathamesh-VirtualBox
[2021-04-04 22:31:56,093] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-04-05T02:27:23.398734+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-04-05T02:27:23.398734+00:00
[2021-04-04 22:31:56,093] {http.py:102} INFO - Poking: api/
[2021-04-04 22:31:56,097] {base.py:65} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: None
[2021-04-04 22:31:56,099] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-04-04 22:31:56,285] {base.py:245} INFO - Success criteria met. Exiting.
[2021-04-04 22:31:56,291] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20210405T022723, start_date=20210405T023155, end_date=20210405T023156
[2021-04-04 22:31:56,317] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-04-04 22:31:56,343] {local_task_job.py:146} INFO - Task exited with return code 0
